<?php

namespace MapsBundle\Repository;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends \Doctrine\ORM\EntityRepository
{
  public function listeVisite($month, $year) {
    $qb = $this->createQueryBuilder('lo');
    $qb->select('lo')->where('lo.month = :month')->setParameter('month', $month)->andWhere('lo.year = :year')->setParameter('year', $year);

    return $qb->getQuery()->getResult();
  }
}
